import { ComplianceFramework } from "@prisma/client";

interface LibraryControl {
  controlId: string;
  controlName: string;
}

// ISO/IEC 27001:2022 Annex A — full 93-control set across the four themes
// (organizational, people, physical, technological). Loaded verbatim so a
// consultant reviews and assesses every control rather than typing each one
// in by hand from scratch.
const ISO27001_CONTROLS: LibraryControl[] = [
  { controlId: "A.5.1", controlName: "Policies for information security" },
  { controlId: "A.5.2", controlName: "Information security roles and responsibilities" },
  { controlId: "A.5.3", controlName: "Segregation of duties" },
  { controlId: "A.5.4", controlName: "Management responsibilities" },
  { controlId: "A.5.5", controlName: "Contact with authorities" },
  { controlId: "A.5.6", controlName: "Contact with special interest groups" },
  { controlId: "A.5.7", controlName: "Threat intelligence" },
  { controlId: "A.5.8", controlName: "Information security in project management" },
  { controlId: "A.5.9", controlName: "Inventory of information and other associated assets" },
  { controlId: "A.5.10", controlName: "Acceptable use of information and other associated assets" },
  { controlId: "A.5.11", controlName: "Return of assets" },
  { controlId: "A.5.12", controlName: "Classification of information" },
  { controlId: "A.5.13", controlName: "Labelling of information" },
  { controlId: "A.5.14", controlName: "Information transfer" },
  { controlId: "A.5.15", controlName: "Access control" },
  { controlId: "A.5.16", controlName: "Identity management" },
  { controlId: "A.5.17", controlName: "Authentication information" },
  { controlId: "A.5.18", controlName: "Access rights" },
  { controlId: "A.5.19", controlName: "Information security in supplier relationships" },
  { controlId: "A.5.20", controlName: "Addressing information security within supplier agreements" },
  { controlId: "A.5.21", controlName: "Managing information security in the ICT supply chain" },
  { controlId: "A.5.22", controlName: "Monitoring, review and change management of supplier services" },
  { controlId: "A.5.23", controlName: "Information security for use of cloud services" },
  { controlId: "A.5.24", controlName: "Information security incident management planning and preparation" },
  { controlId: "A.5.25", controlName: "Assessment and decision on information security events" },
  { controlId: "A.5.26", controlName: "Response to information security incidents" },
  { controlId: "A.5.27", controlName: "Learning from information security incidents" },
  { controlId: "A.5.28", controlName: "Collection of evidence" },
  { controlId: "A.5.29", controlName: "Information security during disruption" },
  { controlId: "A.5.30", controlName: "ICT readiness for business continuity" },
  { controlId: "A.5.31", controlName: "Legal, statutory, regulatory and contractual requirements" },
  { controlId: "A.5.32", controlName: "Intellectual property rights" },
  { controlId: "A.5.33", controlName: "Protection of records" },
  { controlId: "A.5.34", controlName: "Privacy and protection of PII" },
  { controlId: "A.5.35", controlName: "Independent review of information security" },
  { controlId: "A.5.36", controlName: "Compliance with policies, rules and standards for information security" },
  { controlId: "A.5.37", controlName: "Documented operating procedures" },
  { controlId: "A.6.1", controlName: "Screening" },
  { controlId: "A.6.2", controlName: "Terms and conditions of employment" },
  { controlId: "A.6.3", controlName: "Information security awareness, education and training" },
  { controlId: "A.6.4", controlName: "Disciplinary process" },
  { controlId: "A.6.5", controlName: "Responsibilities after termination or change of employment" },
  { controlId: "A.6.6", controlName: "Confidentiality or non-disclosure agreements" },
  { controlId: "A.6.7", controlName: "Remote working" },
  { controlId: "A.6.8", controlName: "Information security event reporting" },
  { controlId: "A.7.1", controlName: "Physical security perimeters" },
  { controlId: "A.7.2", controlName: "Physical entry" },
  { controlId: "A.7.3", controlName: "Securing offices, rooms and facilities" },
  { controlId: "A.7.4", controlName: "Physical security monitoring" },
  { controlId: "A.7.5", controlName: "Protecting against physical and environmental threats" },
  { controlId: "A.7.6", controlName: "Working in secure areas" },
  { controlId: "A.7.7", controlName: "Clear desk and clear screen" },
  { controlId: "A.7.8", controlName: "Equipment siting and protection" },
  { controlId: "A.7.9", controlName: "Security of assets off-premises" },
  { controlId: "A.7.10", controlName: "Storage media" },
  { controlId: "A.7.11", controlName: "Supporting utilities" },
  { controlId: "A.7.12", controlName: "Cabling security" },
  { controlId: "A.7.13", controlName: "Equipment maintenance" },
  { controlId: "A.7.14", controlName: "Secure disposal or re-use of equipment" },
  { controlId: "A.8.1", controlName: "User endpoint devices" },
  { controlId: "A.8.2", controlName: "Privileged access rights" },
  { controlId: "A.8.3", controlName: "Information access restriction" },
  { controlId: "A.8.4", controlName: "Access to source code" },
  { controlId: "A.8.5", controlName: "Secure authentication" },
  { controlId: "A.8.6", controlName: "Capacity management" },
  { controlId: "A.8.7", controlName: "Protection against malware" },
  { controlId: "A.8.8", controlName: "Management of technical vulnerabilities" },
  { controlId: "A.8.9", controlName: "Configuration management" },
  { controlId: "A.8.10", controlName: "Information deletion" },
  { controlId: "A.8.11", controlName: "Data masking" },
  { controlId: "A.8.12", controlName: "Data leakage prevention" },
  { controlId: "A.8.13", controlName: "Information backup" },
  { controlId: "A.8.14", controlName: "Redundancy of information processing facilities" },
  { controlId: "A.8.15", controlName: "Logging" },
  { controlId: "A.8.16", controlName: "Monitoring activities" },
  { controlId: "A.8.17", controlName: "Clock synchronization" },
  { controlId: "A.8.18", controlName: "Use of privileged utility programs" },
  { controlId: "A.8.19", controlName: "Installation of software on operational systems" },
  { controlId: "A.8.20", controlName: "Networks security" },
  { controlId: "A.8.21", controlName: "Security of network services" },
  { controlId: "A.8.22", controlName: "Segregation of networks" },
  { controlId: "A.8.23", controlName: "Web filtering" },
  { controlId: "A.8.24", controlName: "Use of cryptography" },
  { controlId: "A.8.25", controlName: "Secure development life cycle" },
  { controlId: "A.8.26", controlName: "Application security requirements" },
  { controlId: "A.8.27", controlName: "Secure system architecture and engineering principles" },
  { controlId: "A.8.28", controlName: "Secure coding" },
  { controlId: "A.8.29", controlName: "Security testing in development and acceptance" },
  { controlId: "A.8.30", controlName: "Outsourced development" },
  { controlId: "A.8.31", controlName: "Separation of development, test and production environments" },
  { controlId: "A.8.32", controlName: "Change management" },
  { controlId: "A.8.33", controlName: "Test information" },
  { controlId: "A.8.34", controlName: "Protection of information systems during audit testing" },
];

// Nigeria Data Protection Act 2023 / NDPR — unlike ISO 27001 there's no
// official numbered control catalog, so this is a practical compliance
// checklist derived from the Act's core obligations (lawful basis, DPO,
// DPIA, breach notification timelines, data subject rights, cross-border
// transfer safeguards, etc.), not a verbatim reproduction of statutory text.
const NDPR_CONTROLS: LibraryControl[] = [
  { controlId: "NDPR.1", controlName: "Lawful basis for processing identified and documented" },
  { controlId: "NDPR.2", controlName: "Privacy policy/notice published and accessible to data subjects" },
  { controlId: "NDPR.3", controlName: "Data Protection Officer (DPO) appointed where required" },
  { controlId: "NDPR.4", controlName: "Data Protection Impact Assessment (DPIA) conducted for high-risk processing" },
  { controlId: "NDPR.5", controlName: "Consent mechanisms are specific, informed, and freely given (where consent is the lawful basis)" },
  { controlId: "NDPR.6", controlName: "Data minimization — only necessary personal data is collected" },
  { controlId: "NDPR.7", controlName: "Data subject access request (DSAR) process in place" },
  { controlId: "NDPR.8", controlName: "Right to rectification process in place" },
  { controlId: "NDPR.9", controlName: "Right to erasure process in place" },
  { controlId: "NDPR.10", controlName: "Data retention schedule defined and enforced" },
  { controlId: "NDPR.11", controlName: "Cross-border data transfer safeguards in place" },
  { controlId: "NDPR.12", controlName: "Data breach detection and internal escalation process" },
  { controlId: "NDPR.13", controlName: "Data breach notification to NDPC within required timeframe" },
  { controlId: "NDPR.14", controlName: "Data breach notification process for affected data subjects" },
  { controlId: "NDPR.15", controlName: "Data processing agreements in place with third-party processors" },
  { controlId: "NDPR.16", controlName: "Records of processing activities (ROPA) maintained" },
  { controlId: "NDPR.17", controlName: "Staff data-protection awareness training conducted" },
  { controlId: "NDPR.18", controlName: "Technical safeguards implemented (encryption, access control)" },
  { controlId: "NDPR.19", controlName: "Organizational safeguards implemented (policies, periodic access reviews)" },
  { controlId: "NDPR.20", controlName: "Annual data protection compliance audit/filing completed" },
];

export const CONTROL_LIBRARY: Partial<Record<ComplianceFramework, LibraryControl[]>> = {
  ISO27001: ISO27001_CONTROLS,
  NDPR: NDPR_CONTROLS,
};
